  
services:

  client:
    image : ${FRONTEND_REPO}
    restart: on-failure
    ports:
     - ${CLIENT_PORT}
    environment:
      - VITE_API_URL=${VITE_API_URL}
  backend:
    image: ${BACKEND_REPO}
    restart: on-failure
    

    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=${POSTGRES_HOST}
      - PGDATABASE=${POSTGRES_DB}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${DOCKER_SERVER_PORT}
    depends_on:
      - db
  db:
    image: postgres:18
    restart: on-failure 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_DB=${POSTGRES_DB} 
